In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('../../Reviews.csv')
data.describe()

,Id,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
count,568454.000000,568454.000000,568454.00000,568454.000000,5.684540e+05
mean,284227.500000,1.743817,2.22881,4.183199,1.296257e+09
std,164098.679298,7.636513,8.28974,1.310436,4.804331e+07
min,1.000000,0.000000,0.00000,1.000000,9.393408e+08
25%,142114.250000,0.000000,0.00000,4.000000,1.271290e+09
50%,284227.500000,0.000000,1.00000,5.000000,1.311120e+09
75%,426340.750000,2.000000,2.00000,5.000000,1.332720e+09
max,568454.000000,866.000000,923.00000,5.000000,1.351210e+09

In [4]:
data.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [5]:
data = data[data['Score'] != 3]

# napravi novu kolonu Sentiment
data['Sentiment'] = data['Score'].apply(lambda x: 'positive' if x > 3 else 'negative')

In [6]:
print(data['Sentiment'].value_counts())
data.head()

Sentiment
positive    443777
negative     82037
Name: count, dtype: int64

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,Sentiment
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...,positive
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,negative
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,positive
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...,negative
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...,positive

In [7]:
# Pronađi koliko imaš dostupnih negativnih (manjinska klasa)
min_class_size = data['Sentiment'].value_counts().min()

# Uzmi ili 5000 ili koliko god imaš ako je manje od toga
sample_n = min(15000, min_class_size)

negative = data[data['Sentiment'] == 'negative'].sample(n=sample_n, random_state=42)
positive = data[data['Sentiment'] == 'positive'].sample(n=sample_n, random_state=42)

data = pd.concat([negative, positive]).sample(frac=1, random_state=42)

print(data['Sentiment'].value_counts())
print(data.shape)
data.head()

Sentiment
negative    15000
positive    15000
Name: count, dtype: int64
(30000, 11)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,Sentiment
62747,62748,B000I1OLT2,A3U7LZDJ6ZF3AU,Poodle Mom,1,5,1,1288137600,Not if you like Salada Green Chai Tea,"I'd never tried this before, but because I lik...",negative
531798,531799,B005K4Q34S,A3NS0YMSWNF8HP,she say whaaaat?,0,0,5,1332460800,Just what I'd hoped for!,I bought this coffee after reading multiple re...,positive
57334,57335,B00817GPWQ,A1PWRVOY3M2SAO,SurferGurl96770,1,1,5,1273276800,Decadent In A Good Kind Of Way,When I opened the box the aroma of this coffee...,positive
169879,169880,B000FBM480,A1VBQ8ANDKZWTE,L. Weng,0,0,5,1273536000,Wonderful Taste,"It tastes perfect. I like it.<br />You would ""...",positive
333692,333693,B00472GKC4,A19YA6BM16GT8D,qona,3,4,1,1320451200,They changed the recipe! No longer tasty,But it's just as well as they aren't good for ...,negative

In [9]:
# sačuvaj kao CSV fajl
data.to_csv('Reviews_sample_balanced1.csv', index=False)

print("Fajl sacuvan kao Reviews_sample_balanced1.csv")

Fajl sacuvan kao Reviews_sample_balanced1.csv